# Uncomment the next line to define a global platform for your project
inhibit_all_warnings!
platform :ios, '13.2'
use_frameworks!

target 'SocketApp' do
  pod 'SocketIO'
  pod 'Google-Mobile-Ads-SDK', '~> 7.51'
  pod 'Firebase', '~> 6.11'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
  pod 'SwiftSocket'
end
